baseURL = "/"
languageCode = "en-us"
title = "nilstriebs blog"
theme = "terminal"

[author]
name = "Nilstrieb"

[params]
contentTypeName = "posts"
themeColor = "orange"
centerTheme = true

[params.logo]
logoText = "nilstriebs blog"
