baseURL = "/"
languageCode = "en-us"
title = "Noratrieb's blog"
theme = "terminal"

[author]
name = "Noratrieb"

[params]
contentTypeName = "posts"
themeColor = "orange"
centerTheme = true

[params.logo]
logoText = "noratrieb's blog"

# Let me use HTML :3
[markup.goldmark.renderer]
unsafe = true
